In [7]:
import numpy as np
import pandas as pd

In [3]:
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [4]:
!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

 93% 24.0M/25.7M [00:01<00:00, 24.8MB/s]
100% 25.7M/25.7M [00:01<00:00, 16.0MB/s]


In [5]:
!unzip imdb-dataset-of-50k-movie-reviews.zip -d data

Archive:  imdb-dataset-of-50k-movie-reviews.zip
  inflating: data/IMDB Dataset.csv   


In [8]:
temp_df = pd.read_csv('/content/data/IMDB Dataset.csv')

In [9]:
df = temp_df.iloc[:10000]

In [10]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [11]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [12]:
df['sentiment'].value_counts()

positive    5028
negative    4972
Name: sentiment, dtype: int64

In [14]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [15]:
df.duplicated().sum()

17

In [16]:
df.drop_duplicates(inplace=True)

<ipython-input-16-16cdb8520be8>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [17]:
df.duplicated().sum()

0

# Basic Preprocessing
# Remove tags
# lowercase
# remove stopwords

In [20]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [21]:
df['review'] = df['review'].apply(remove_tags)

<ipython-input-21-00e93c2a3043>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [22]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [23]:
df['review'] = df['review'].apply(lambda x:x.lower())

<ipython-input-23-afca29351ee0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


In [26]:
import nltk
nltk.download('all')
from nltk.corpus import stopwords

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-dat

In [27]:
sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

<ipython-input-27-62552e08616c>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [29]:
df

review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [30]:
X = df.iloc[:,0:1]
y = df['sentiment']

In [31]:
X

review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [32]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [33]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [34]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [36]:
X_train.shape

(7986, 1)

In [37]:
# Applying BoW
from sklearn.feature_extraction.text import CountVectorizer

In [38]:
cv = CountVectorizer()

In [57]:
X_train_bow = cv.fit_transform(X_train['review']).toarray() #convert scipy.sparse._csr.csr_matrix to array
X_test_bow = cv.transform(X_test['review']).toarray()

In [58]:
X_train_bow.shape

(7986, 48282)

In [59]:
type(X_train_bow)

numpy.ndarray

In [60]:
type(y_train)

numpy.ndarray

In [61]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train_bow,y_train)

GaussianNB()

In [62]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6324486730095142

In [63]:
confusion_matrix(y_test,y_pred)

array([[717, 235],
       [499, 546]])

In [64]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8497746619929895

In [65]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8377566349524287

In [66]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8447671507260891

## Using TfIdf

In [67]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [68]:
tfidf = TfidfVectorizer()

In [69]:
X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])

In [70]:
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8442663995993991

**Applying Word2Vec**

In [72]:
import gensim

In [73]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [74]:
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))


In [76]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)
# window (int, optional) – Maximum distance between the current and predicted word within a sentence.
# min_count (int, optional) – Ignores all words with total frequency lower than this.

In [77]:
model.build_vocab(story)

In [78]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(5876441, 6212140)

In [79]:
len(model.wv.index_to_key)

31845

In [80]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [81]:
document_vector(df['review'].values[0])

array([-0.20109549,  0.5294996 ,  0.1879305 ,  0.2653875 , -0.11227485,
       -0.6607593 ,  0.21916789,  0.97164184, -0.33408767, -0.28695834,
       -0.2458622 , -0.47757074,  0.11079872,  0.14093788,  0.22542617,
       -0.14265525,  0.00784361, -0.29595044, -0.05135798, -0.6227985 ,
       -0.02619318,  0.25589037,  0.07948315, -0.3165459 , -0.27768773,
        0.0229198 , -0.28547883, -0.01549816, -0.3692234 ,  0.05911288,
        0.3232744 , -0.0115837 ,  0.17754893, -0.30129287, -0.192984  ,
        0.47620454,  0.03095777, -0.37080938, -0.22270943, -0.7577047 ,
        0.12306056, -0.23622021,  0.0653337 , -0.01172615,  0.5324307 ,
       -0.09747043, -0.21285863, -0.03418277,  0.06660429,  0.36049533,
        0.06050937, -0.36940378, -0.40658623, -0.16351128, -0.10522174,
        0.21680425,  0.19652052,  0.0435159 , -0.2861667 ,  0.05165365,
        0.04837437,  0.05863232, -0.00103309, -0.0542331 , -0.3927262 ,
        0.25477177,  0.0418544 ,  0.11620788, -0.40415588,  0.23

In [82]:
from tqdm import tqdm


In [83]:
X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████| 9983/9983 [10:39<00:00, 15.60it/s]


In [84]:
X = np.array(X)

In [85]:
X[0]

array([-0.20109549,  0.5294996 ,  0.1879305 ,  0.2653875 , -0.11227485,
       -0.6607593 ,  0.21916789,  0.97164184, -0.33408767, -0.28695834,
       -0.2458622 , -0.47757074,  0.11079872,  0.14093788,  0.22542617,
       -0.14265525,  0.00784361, -0.29595044, -0.05135798, -0.6227985 ,
       -0.02619318,  0.25589037,  0.07948315, -0.3165459 , -0.27768773,
        0.0229198 , -0.28547883, -0.01549816, -0.3692234 ,  0.05911288,
        0.3232744 , -0.0115837 ,  0.17754893, -0.30129287, -0.192984  ,
        0.47620454,  0.03095777, -0.37080938, -0.22270943, -0.7577047 ,
        0.12306056, -0.23622021,  0.0653337 , -0.01172615,  0.5324307 ,
       -0.09747043, -0.21285863, -0.03418277,  0.06660429,  0.36049533,
        0.06050937, -0.36940378, -0.40658623, -0.16351128, -0.10522174,
        0.21680425,  0.19652052,  0.0435159 , -0.2861667 ,  0.05165365,
        0.04837437,  0.05863232, -0.00103309, -0.0542331 , -0.3927262 ,
        0.25477177,  0.0418544 ,  0.11620788, -0.40415588,  0.23

In [86]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [87]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [88]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [89]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7676514772158237